services:
  - type: web
    name: pos-api
    runtime: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: pnpm install --frozen-lockfile --prod=false && npx turbo run build --filter=@pos/api && cd apps/api && npx prisma migrate deploy && node --loader ts-node/esm prisma/seed.ts
    startCommand: cd apps/api && node dist/main.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: PLATFORM_ADMIN_EMAIL
        sync: false
      - key: PLATFORM_ADMIN_PASSWORD
        sync: false
      - key: PLATFORM_ADMIN_FIRST_NAME
        value: Platform
      - key: PLATFORM_ADMIN_LAST_NAME
        value: Admin
